### ISSUE TITLE
Version 2 Roadmap

### ISSUE THREAD

**Issue by dmolineus** [contao-community-alliance/meta-palettes#35]
- [ ] Contao 4 only
- [ ] Namespace ändern
- [ ] Kompatibilität mit Contao 4 prüfen (Subselectmetapalettes und Contaos sub sub palettes)
- [ ] Überprüfung des MetaPalettes Builder mit dem DCG
- [ ] Refactoring
- [ ] Ggf. Verwendung des Palette-Manipulators

**Comment by dmolineus** [comment]
Closed in favor of #36.
